export const data = [
    {
      staff_id: 491,
      staff_name: 'Sania',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'MATHEMATICS',
      total_no_of_leaves: 10,
      staff_taken_leaves: 2,
      subjects: [
        {
          subject_id: 108,
          classroom_id: 890,
          classroom_std: 10,
          classroom_name: 'Kalam',
          classroom_section: 'A',
          subject_name: 'MATHEMATICS',
          secure_percentage: 90,
          target_str: '80%',
        },
      ],
      tot_working_days: '450',
      attended_days: '360',
    },
    {
      staff_id: 492,
      staff_name: 'Amit',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'ENGLISH',
      total_no_of_leaves: 12,
      staff_taken_leaves: 3,
      subjects: [
        {
          subject_id: 109,
          classroom_id: 891,
          classroom_std: 11,
          classroom_name: 'Einstein',
          classroom_section: 'B',
          subject_name: 'ENGLISH',
          secure_percentage: 85,
          target_str: '75%',
        },
      ],
      tot_working_days: '440',
      attended_days: '350',
    },
    {
      staff_id: 493,
      staff_name: 'Priya',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'SCIENCE',
      total_no_of_leaves: 8,
      staff_taken_leaves: 1,
      subjects: [
        {
          subject_id: 110,
          classroom_id: 892,
          classroom_std: 12,
          classroom_name: 'Newton',
          classroom_section: 'C',
          subject_name: 'SCIENCE',
          secure_percentage: 88,
          target_str: '78%',
        },
      ],
      tot_working_days: '460',
      attended_days: '370',
    },
    {
      staff_id: 494,
      staff_name: 'Rahul',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'SOCIAL STUDIES',
      total_no_of_leaves: 15,
      staff_taken_leaves: 5,
      subjects: [
        {
          subject_id: 111,
          classroom_id: 893,
          classroom_std: 9,
          classroom_name: 'Galileo',
          classroom_section: 'D',
          subject_name: 'SOCIAL STUDIES',
          secure_percentage: 80,
          target_str: '70%',
        },
      ],
      tot_working_days: '430',
      attended_days: '340',
    },
    {
      staff_id: 495,
      staff_name: 'Ravi',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'HISTORY',
      total_no_of_leaves: 9,
      staff_taken_leaves: 2,
      subjects: [
        {
          subject_id: 112,
          classroom_id: 894,
          classroom_std: 10,
          classroom_name: 'Curie',
          classroom_section: 'E',
          subject_name: 'HISTORY',
          secure_percentage: 75,
          target_str: '65%',
        },
      ],
      tot_working_days: '420',
      attended_days: '330',
    },
    {
      staff_id: 496,
      staff_name: 'Neha',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'GEOGRAPHY',
      total_no_of_leaves: 11,
      staff_taken_leaves: 4,
      subjects: [
        {
          subject_id: 113,
          classroom_id: 895,
          classroom_std: 11,
          classroom_name: 'Darwin',
          classroom_section: 'F',
          subject_name: 'GEOGRAPHY',
          secure_percentage: 82,
          target_str: '72%',
        },
      ],
      tot_working_days: '450',
      attended_days: '355',
    },
    {
      staff_id: 497,
      staff_name: 'Sunita',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'PHYSICS',
      total_no_of_leaves: 14,
      staff_taken_leaves: 6,
      subjects: [
        {
          subject_id: 114,
          classroom_id: 896,
          classroom_std: 12,
          classroom_name: 'Tesla',
          classroom_section: 'G',
          subject_name: 'PHYSICS',
          secure_percentage: 89,
          target_str: '79%',
        },
      ],
      tot_working_days: '470',
      attended_days: '375',
    },
    {
      staff_id: 498,
      staff_name: 'Vikas',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'CHEMISTRY',
      total_no_of_leaves: 13,
      staff_taken_leaves: 5,
      subjects: [
        {
          subject_id: 115,
          classroom_id: 897,
          classroom_std: 9,
          classroom_name: 'Bohr',
          classroom_section: 'H',
          subject_name: 'CHEMISTRY',
          secure_percentage: 78,
          target_str: '68%',
        },
      ],
      tot_working_days: '440',
      attended_days: '350',
    },
    {
      staff_id: 499,
      staff_name: 'Anita',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'BIOLOGY',
      total_no_of_leaves: 7,
      staff_taken_leaves: 1,
      subjects: [
        {
          subject_id: 116,
          classroom_id: 898,
          classroom_std: 10,
          classroom_name: 'Linnaeus',
          classroom_section: 'I',
          subject_name: 'BIOLOGY',
          secure_percentage: 92,
          target_str: '82%',
        },
      ],
      tot_working_days: '460',
      attended_days: '365',
    },
    {
      staff_id: 500,
      staff_name: 'Arjun',
      staff_photo: '',
      staff_inst_id: '',
      staff_main_subject: 'COMPUTER SCIENCE',
      total_no_of_leaves: 6,
      staff_taken_leaves: 2,
      subjects: [
        {
          subject_id: 117,
          classroom_id: 899,
          classroom_std: 12,
          classroom_name: 'Turing',
          classroom_section: 'J',
          subject_name: 'COMPUTER SCIENCE',
          secure_percentage: 95,
          target_str: '85%',
        },
      ],
      tot_working_days: '480',
      attended_days: '380',
    },
  ];